/**
 * This aspect tells the recipient if the CX is successfully generated by the source
 */
export interface Status {
  /**
   * When an error occurs during the creation of the CX network,
   * the source can write out a status aspect to the CX stream with some error message in it and finish the CX network immediately
   */
  error: string;

  /**
   * Success fields tells if the cx document is successfully generated by the source
   */
  success: boolean;
}
